# Computing Mathematics II - Tutorial 6

In [1]:
import numpy as np

## Question 1
<img src="Questions\Q1.jpg">

In [8]:
u = np.array([2,-7,1])
v = np.array([-3,0,4])
w = np.array([0,5,-8])

ans = 3*u - 4*v
print(ans)

[ 18 -21 -13]


In [9]:
ans = 2*u + 3*v - 5*w
print(ans)

[ -5 -39  54]


## Question 4
<img src="Questions\Q4.jpg">

In [10]:
A = np.array([[1,4,-3],[6,3,0]])
B = np.array([[3,2,1],[-2,-6,-5]])
C = np.array([[2,4],[4,0],[-2,2]])
alpha = 4
beta = 0.5

ans = {
    "a":A + B,
    "c":B.transpose() + C,
    "e":beta*C,
    "f":4*A - 3*B,
    "g":A.transpose() + alpha*C,
    "h":A+B-C.transpose(),
    "i":4*A+2*B-5*C.transpose()
}

for key in ans:
    print(key,"\n",ans[key])


a 
 [[ 4  6 -2]
 [ 4 -3 -5]]
c 
 [[ 5  2]
 [ 6 -6]
 [-1 -3]]
e 
 [[ 1.  2.]
 [ 2.  0.]
 [-1.  1.]]
f 
 [[ -5  10 -15]
 [ 30  30  15]]
g 
 [[  9  22]
 [ 20   3]
 [-11   8]]
h 
 [[ 2  2  0]
 [ 0 -3 -7]]
i 
 [[  0   0   0]
 [  0   0 -20]]


## Question 5
<img src="Questions/Q5.jpg">

In [11]:
A = np.array([[1,3],[6,2]])
B = np.array([[-2,3,-2],[-4,-2,1],[2,4,2]])
print("det(A):",round(np.linalg.det(A)))
print("det(B):",round(np.linalg.det(B)))

det(A): -16.0
det(B): 70.0


## Question 8
<img src="Questions/Q8.jpg">

In [5]:
A = np.array([[1,0,1],[1,1,1],[2,-1,1]])
A_inv = np.linalg.inv(A)
A_inv

array([[-2.,  1.,  1.],
       [-1.,  1.,  0.],
       [ 3., -1., -1.]])

In [7]:
B = np.array([[1,3,1],[0,2,1],[2,2,1]])
B_inv = np.linalg.inv(B)
B_inv

array([[ 0. , -0.5,  0.5],
       [ 1. , -0.5, -0.5],
       [-2. ,  2. ,  1. ]])

## Question 9
<img src="Questions/Q9.jpg">


In [14]:
A = np.array([[1,-1,2],[1,0,-2],[2,-1,-1]])
Y = np.array([5,8,-6])
X = np.linalg.inv(A).dot(Y)

for i in range(1, len(X) + 1):
    print("X{i} = {x}".format(i=i,x=X[i-1]))

X1 = 46.0
X2 = 79.0
X3 = 19.0


## References
1. NumPy for Vectors and Matrices
-  https://www2.lawrence.edu/fast/GREGGJ/Python/numpy/numpyLA.html